env:
  - NODE_ENV=test

services:
  - docker

script:
  - docker ps | grep -q myst

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
