language: node_js

node_js:
  - '10.15.3'
  - '12.3.1'

env:
  - NODE_ENV=test

services:
  - docker

install:
  - npm install

script: npm test

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
