language: node_js

services:
  - docker

before_install:
  - docker build -t slavapavlutin/mystery-project .
  - docker ps -a
  - docker run slavapavlutin/mystery-project /bin/sh -c "npm test"

install:
  - npm install

script:
  - npm test
