plugins:
  - removeDoctype
  - removeXMLProcInst
  - removeComments
  - removeMetadata
  - removeXMLNS
  - removeEditorsNSData
  - inlineStyles
  - minifyStyles
  - convertStyleToAttrs
  - prefixIds
  - convertColors
  - removeUnknownsAndDefaults
  - removeNonInheritableGroupAttrs
  - removeUselessStrokeAndFill
  - removeViewBox
  - cleanupEnableBackground
  - removeHiddenElems
  - removeEmptyText
  - convertShapeToPath
  - moveElemsAttrsToGroup
  - moveGroupAttrsToElems
  - collapseGroups
  - convertTransform
  - removeEmptyAttrs
  - removeEmptyContainers
  - mergePaths
  - removeUnusedNS
  - sortAttrs
  - removeDimensions
  - removeAttributesBySelector
  - removeElementsByAttr
  - addClassesToSVGElement
  - removeScriptElement
  - addAttributesToSVGElement
  - removeOffCanvasPaths
  - removeStyleElement
  - removeTitle
  - removeDesc
  - removeUselessDefs
  - removeDimensions
  - removeRasterImages
  - reusePaths
  - cleanupIDs
  - cleanupAttrs
  - removeAttrs:
      attrs: '(class|id|data-name)'
  - cleanupNumericValues:
      floatPrecision: 2
  - cleanupListOfValues:
      floatPrecision: 2
  - convertPathData:
      floatPrecision: 1
